#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 11 13:15:30 2018

cargart y gaficar datos de kaggle con pandas

@author: sebalander
"""
# %% imports and script constants
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

datafile = "./Data/bitstampUSD_1-min_data_2012-01-01_to_2018-01-08.csv"

# %% load data and plot closing price

data = pd.read_csv(datafile)
data.plot(x='Timestamp', y='Close')
